language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
env:
    - DJANGO_SETTINGS_MODULE=rankme.settings.test
install:
    - pip install -r requirements/base.txt --use-mirrors
script:
    - python manage.py test
